# Generated by Django 4.1.1 on 2022-09-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebadb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programador',
            name='lenguaje',
        ),
        migrations.DeleteModel(
            name='Lenguaje',
        ),
    ]
