# Generated by Django 4.1.1 on 2022-09-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebadb', '0002_remove_programador_lenguaje_delete_lenguaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('creador', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='programador',
            name='lenguaje',
            field=models.ManyToManyField(to='pruebadb.lenguaje'),
        ),
    ]
